using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SVG2Poly.Helpers
{
	//[GENERATED by DEEPSEEK]
	public class GCMemoryInfoFormatter
	{
		public static string Format(GCMemoryInfo gcInfo)
		{
			var sb = new StringBuilder();

			sb.AppendLine("=== Garbage Collection Memory Information ===");
			sb.AppendLine($"Generation: {gcInfo.Generation}");
			sb.AppendLine($"High Memory Load Threshold: {FormatBytes(gcInfo.HighMemoryLoadThresholdBytes)}");
			sb.AppendLine($"Memory Load: {FormatBytes(gcInfo.MemoryLoadBytes)}");
			sb.AppendLine($"Total Available Memory: {FormatBytes(gcInfo.TotalAvailableMemoryBytes)}");
			sb.AppendLine($"Heap Size: {FormatBytes(gcInfo.HeapSizeBytes)}");
			sb.AppendLine($"Fragmented Heap Size: {FormatBytes(gcInfo.FragmentedBytes)}");
			sb.AppendLine($"Index: {gcInfo.Index}");
			sb.AppendLine($"Generation: {gcInfo.Generation}");
			sb.AppendLine($"Compacted: {gcInfo.Compacted}");
			sb.AppendLine($"Concurrent: {gcInfo.Concurrent}");
			sb.AppendLine($"Pause Duration: {gcInfo.PauseTimePercentage:F2}%");

			// GC Generation sizes
			sb.AppendLine("\n--- Generation Sizes ---");
			sb.AppendLine($"Generation 0: {FormatBytes(gcInfo.GenerationInfo[0].SizeAfterBytes)}");
			sb.AppendLine($"Generation 1: {FormatBytes(gcInfo.GenerationInfo[1].SizeAfterBytes)}");
			sb.AppendLine($"Generation 2: {FormatBytes(gcInfo.GenerationInfo[2].SizeAfterBytes)}");

			// Pause durations
			if (gcInfo.PauseDurations != null && gcInfo.PauseDurations.Length > 0)
			{
				sb.AppendLine("\n--- Pause Durations ---");
				for (int i = 0; i < gcInfo.PauseDurations.Length; i++)
				{
					sb.AppendLine($"Pause {i + 1}: {gcInfo.PauseDurations[i].TotalMilliseconds:F2}ms");
				}
			}

			// Finalization info
			sb.AppendLine("\n--- Finalization ---");
			sb.AppendLine($"Finalization Pending Count: {gcInfo.FinalizationPendingCount}");

			// Promoted bytes
			sb.AppendLine("\n--- Promotion ---");
			sb.AppendLine($"Promoted Bytes: {FormatBytes(gcInfo.PromotedBytes)}");

			// Pinned objects
			sb.AppendLine($"Pinned Objects Count: {gcInfo.PinnedObjectsCount}");

			return sb.ToString();
		}

		public static string FormatCompact(GCMemoryInfo gcInfo)
		{
			return $"GC#{gcInfo.Index} Gen{gcInfo.Generation} | " +
				   $"Heap: {FormatBytes(gcInfo.HeapSizeBytes)} | " +
				   $"Gen 2: {FormatBytes(gcInfo.GenerationInfo[2].SizeAfterBytes)}" +
				   $"Fragmented: {FormatBytes(gcInfo.FragmentedBytes)} | " +
				   $"Pause: {gcInfo.PauseTimePercentage:F1}% | " +
				   $"Compacted: {gcInfo.Compacted}";
		}

		public static string FormatAsJson(GCMemoryInfo gcInfo)
		{
			var json = new StringBuilder();
			json.Append("{");
			json.Append($"\"generation\": {gcInfo.Generation},");
			json.Append($"\"index\": {gcInfo.Index},");
			json.Append($"\"heapSizeBytes\": {gcInfo.HeapSizeBytes},");
			json.Append($"\"fragmentedBytes\": {gcInfo.FragmentedBytes},");
			json.Append($"\"highMemoryLoadThresholdBytes\": {gcInfo.HighMemoryLoadThresholdBytes},");
			json.Append($"\"memoryLoadBytes\": {gcInfo.MemoryLoadBytes},");
			json.Append($"\"totalAvailableMemoryBytes\": {gcInfo.TotalAvailableMemoryBytes},");
			json.Append($"\"compacted\": {gcInfo.Compacted.ToString().ToLower()},");
			json.Append($"\"background\": {gcInfo.Concurrent.ToString().ToLower()},");
			json.Append($"\"pauseDurationPercentage\": {gcInfo.PauseTimePercentage},");
			json.Append($"\"promotedBytes\": {gcInfo.PromotedBytes},");
			json.Append($"\"pinnedObjectsCount\": {gcInfo.PinnedObjectsCount},");
			json.Append($"\"finalizationPendingCount\": {gcInfo.FinalizationPendingCount}");
			json.Append("}");

			return json.ToString();
		}

		private static string FormatBytes(long bytes)
		{
			string[] suffixes = { "B", "KB", "MB", "GB", "TB" };
			int counter = 0;
			decimal number = bytes;

			while (Math.Round(number / 1024) >= 1)
			{
				number /= 1024;
				counter++;
			}

			return $"{number:n2} {suffixes[counter]}";
		}
	}

	// Example usage class
	public class GCInfoReporter
	{
		public static void ReportCurrentGCInfoToFile(string FilePath)
		{
			try
			{
				// Get GC memory info (this is typically called during or after a GC)
				var gcInfo = GC.GetGCMemoryInfo();


				File.AppendAllText(FilePath, GCMemoryInfoFormatter.Format(gcInfo));


			}
			catch (Exception ex)
			{
				Console.WriteLine($"Error reporting GC info: {ex.Message}");
			}
		}


		public static void ReportCurrentGCInfoToLog()
		{

			// Get GC memory info (this is typically called during or after a GC)
			var gcInfo = GC.GetGCMemoryInfo();


#if DEBUG

			Debug.WriteLine(GCMemoryInfoFormatter.FormatCompact(gcInfo));

#endif

			Console.WriteLine(GCMemoryInfoFormatter.FormatCompact(gcInfo));





		}



	}
}
